### PR TITLE
Update parameter to select a spicdb datastore

### PR DESCRIPTION
**Pull request by kevinetienne**
Related to #21 

 - `--datastore-kind` -> `--datastore-engine`
 - `--datastore-engine=memdb` -> `--datastore-engine=memory`

### CODE REVIEW

**Comment by jzelinskie** [comment]
Hey there! Thanks for the PR -- this change looks good to me. If you could sign the CLA (just by responding to this GitHub thread), then I can merge this PR.

**Comment by kevinetienne** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kevinetienne** [comment]
recheck

**Comment by kevinetienne** [comment]
Thanks and sorry I've done a typo in the commit, I think you should be able to fix it when merging it to main.

**Review by jzelinskie — APPROVED** [review]

**Pull request merged**
