### PR TITLE
docusaurus: hide light/dark switch, use OS setting

### PR DESCRIPTION
**Pull request by jzelinskie**

### CODE REVIEW

**Review by samkim — APPROVED** [review]
LGTM

**Comment by ecordell** [comment]
I don't have a strong opinion here, but why not respect the os default but leave the toggle? I slightly prefer the light theme even though my OS is dark theme.

**Comment by jzelinskie** [comment]
We could do that. I'd rather improve the dark theme so that you don't mind it, though.

**Comment by samkim** [comment]
Are there things to improve about the dark theme that stand out or just a general preference for reading docs in light theme?

**Pull request merged**
