### PR TITLE
Fix link to first-app guide

### PR DESCRIPTION
**Pull request by fd-automox**
This file is already relative to `guides`, which leads to the following URL (https://docs.authzed.com/guides/guides/first-app) when navigating from https://docs.authzed.com/guides/schema#get-started-for-real.

### CODE REVIEW

**Comment by fd-automox** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fd-automox** [comment]
recheck

**Comment by jzelinskie** [comment]
Thanks for the PR!

We've tried to consistently use the absolute path, so the ideal value is actually `/guides/first-app` for the URL.
If you don't mind updating your PR, I'd be glad to merge it.

**Comment by fd-automox** [comment]
> Thanks for the PR!
> 
> We've tried to consistently use the absolute path, so the ideal value is actually `/guides/first-app` for the URL. If you don't mind updating your PR, I'd be glad to merge it.

Should be gtg, thanks for taking a look!

**Review by jzelinskie — APPROVED** [review]

**Pull request merged**
